from langchain_project_learning import ContentState
from typing import List
from pydantic import Field, BaseModel
from operator import itemgetter
from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from dotenv import load_dotenv
import os
load_dotenv()

os.environ["GROQ_API_KEY"] = os.environ.get("GROQ_API_KEY")

class ValidateResult(BaseModel):
    is_valid: bool = Field(description="Whether the input is valid")
    confidence: float = Field(description="Confidence level of the validation")

    issues: List[str] = Field(description="List of hallucination issues found")



def validate_results(state: ContentState) -> ContentState:
    llm = ChatGroq(temperature=0, model="llama-3.3-70b-versatile")
    input = {
        "synthesize_data" : itemgetter("synthesized_content"),
        "summary" : itemgetter("draft_content")
    }
    prompt = ChatPromptTemplate.from_template(""""
    You are a QA Engineer who is an expert in validating the data and comparing LLM hallucinations from what data we gave and what summary it generated for us 
    Provided are two inputs one is the data we gave and the other is the summary generated by the LLM Model, you need to validate the summary generated by the LLM Model and compare it with the data we gave and return the result in structured output.
    Provided is the data we gave and the summary generated by the LLM Model.
    your task is to generate the confident score out of 100 and the issues and hallucinations found in the summary generated by the LLM Model.
    {synthesize_data}
    Provided is the summary generated by the LLM Model.
    {summary}
    """)

    chain = input | prompt | llm.with_structured_output(ValidateResult) 

    result = chain.invoke(state)


    if result.is_valid:
        state["validation_passed"] = result.is_valid
        state["validation_confidence"] = result.confidence
        state["final_content"] = state["draft_content"]
    else:
        state["validation_passed"] = False
        state["validation_confidence"] = result.confidence
        state["final_content"] = None
        state["validation_issues"] = result.issues
    return state
